### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by le9i0nx**
in my ansible 2 I did not work the old code.
do not create files in the directory /etc/tinc/{{ tinc_network }}/hosts/\* when you add new nodes to the group.
Let's see what is written in the role I have decided that it is easier to copy part of the code.

### CODE REVIEW

**Comment by le9i0nx** [comment]
I have not tested compatibility with ansible <2

**Comment by drybjed** [comment]
I actually have a rework of this role which should work fine with Ansible 2 as well as Ansible 1.x. How about this - I'll make a counter-PR and we'll see if that version works for you?

**Comment by le9i0nx** [comment]
I do not understand the question. "google translate" poor translation.
express it differently

**Comment by drybjed** [comment]
@le9i0nx I have updated this role to work with Ansible 2 and new `debops-playbooks` layout, but I haven't yet pushed the changes to the repository. I'll try to commit them before the weekend and then you could see if these changes work for you instead of your own? The modifications I've made include support for multiple `tinc` VPNs in one role, among other things.

**Comment by le9i0nx** [comment]
It's good.
I will test on my test environment.
pull close later

**Comment by drybjed** [comment]
@le9i0nx New version of `debops.tinc` is up, you might want to check it out.

**Pull request closed without merging**
