### PR TITLE
fix docs tinc__host_addresses: []

### PR DESCRIPTION
**Pull request by le9i0nx**

### CODE REVIEW

**Comment by drybjed** [comment]
@le9i0nx The `tinc__host_addresses_ip` is already a list. Do you have any issues with it? Can you show the contents of this var in a debug task?

**Comment by drybjed** [comment]
Although you might have a point! I stand corrected, both `tinc__host_addresses_ip` and `tinc__host_addresses_fqdn` need to return the same type of value for `tinc__host_addresses`. I would change the `_fqdn` to a list though, might be more portable.

**Comment by le9i0nx** [comment]
I use gray IP address.
tinc__host_addresses: ['{{ ansible_eth0.ipv4.address }}']
From the documentation, I just do not understand that there must be a list.

**Comment by drybjed** [comment]
@le9i0nx To be honest, it doesn't have to be a list. I try to write roles that take care of detecting if user provided a string or a list in the inventory and handle both cases; `debops.tinc` should work no matter if you specify a string or a list in `tinc__host_addresses`. So, did you have any issues with it?

**Comment by drybjed** [comment]
I suspect that this might have been the problem: https://github.com/debops/ansible-tinc/blob/314bcaddec34e873b8eea4e383af9e9439ef4051/templates/etc/tinc/network/hosts/hostname.j2#L21

I test it out and fix it to handle both cases.

**Pull request closed without merging**
